### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/google-apputils#1]
```
It would be nice to have the bits necessary to build Debian package included in 
the tree, similar to how python-gflags does it.

I've attached a patch that will accomplish this.  I may submit this package to 
Debian proper at some point.

(the end result of this should be a debian directory inside your source tree)
```

Original issue reported on code.google.com by `ben...@google.com` on 7 Sep 2010 at 11:17

Attachments:
- [debian_packaging.patch](https://storage.googleapis.com/google-code-attachments/google-apputils-python/issue-1/comment-0/debian_packaging.patch)

**Comment by gpshead** [comment]
We won't be fixing issues directly in this repository.  Development of this library has been moved to https://github.com/abseil/abseil-py.  If it can be reproduced there, please open an issue in the abseil-py project.
