### ISSUE TITLE
Transferring mox?

### ISSUE THREAD

**Issue by jakirkham** [google/google-apputils#11]
Kind of off topic, but it seems [`mox`](https://code.google.com/p/pymox/) hasn't been transferred yet. Is that planned to happen at some point?

**Comment by gpshead** [comment]
thanks, i've started poking the right people to get that updated.

**Comment by jakirkham** [comment]
Awesome. Thanks for looking into it.

**Comment by jakirkham** [comment]
Just wanted to check in @gpshead and see if there was any news on the transfer of `mox`. It appears it is no longer reachable from Google Code.

**Comment by gpshead** [comment]
fyi - while I figure this out the old pymox site is still available via the archive on https://code.google.com/archive/p/pymox/

**Comment by gpshead** [comment]
I've pointed https://pypi.python.org/pypi/mox at a github repo. It is one someone else created, but as the project isn't active that'll do for now. We may swing that link over to one within the /google/ organization if we intend to do any work on it.

**Comment by jakirkham** [comment]
cc @glasser

**Comment by glasser** [comment]
I have not worked at Google or on Mox for a long time. (Mox was never really my project - I did the legwork to get it open sourced so I could use it in a different Google open source project but that different project went in another direction and didn't end up actually needing Mox.)
