### ISSUE TITLE
setup.py should import ez_setup only as a fallback

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/google-apputils#7]
```
Many (most?) environments today will already have setuptools present.

Please provide any additional information below.

See the attached patch.


```

Original issue reported on code.google.com by `tres.sea...@gmail.com` on 22 Oct 2014 at 5:52

Attachments:
- [ez_setup_fallback.patch](https://storage.googleapis.com/google-code-attachments/google-apputils-python/issue-7/comment-0/ez_setup_fallback.patch)

**Comment by gpshead** [comment]
We won't be fixing issues directly in this repository.  Development of this library has been moved to https://github.com/abseil/abseil-py.  If it can be reproduced there, please open an issue in the abseil-py project.
