### ISSUE TITLE
Patch for /trunk/setup.py

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/google-apputils#8]
```
Adding description to setup.py
```

Original issue reported on code.google.com by `kianse...@gmail.com` on 21 Feb 2015 at 3:07

Attachments:
- [setup.py.patch](https://storage.googleapis.com/google-code-attachments/google-apputils-python/issue-8/comment-0/setup.py.patch)

**Comment by gpshead** [comment]
We won't be fixing issues directly in this repository.  Development of this library has been moved to https://github.com/abseil/abseil-py.  If it can be reproduced there, please open an issue in the abseil-py project.
